name: clickhouse
version: "v1.0"
summary: Column-oriented database management system
description: |
    ClickHouse is a fast open-source column-oriented database management system 
    that allows generating analytical data reports in real-time using SQL queries.

base: core20
grade: devel
confinement: devmode

parts:
    clickhouse:
        plugin: dump
        source: .
        stage: [clickhouse]

apps:
    clickhouse:
        command: clickhouse
